trigger:
  - master
  - rel/*

pr:
  - master
  - rel/*

pool:
  vmImage: windows-latest

variables:
  BuildConfiguration: Release

steps:
- task: DotNetCoreCLI@2
  inputs:
    command: custom
    custom: tool
    arguments: install --tool-path . nbgv
  displayName: Install NBGV tool

- script: nbgv cloud
  displayName: Set NBGV Version

- task: DotNetCoreCLI@2
  inputs:
    command: build
    projects: '**/*.csproj'
    arguments: -c $(BuildConfiguration)
  displayName: Build

- task: DotNetCoreCLI@2
  inputs:
    command: pack
    packagesToPack: 'SingleInstanceHelper/*.csproj'
    configuration: $(BuildConfiguration)
    packDirectory: $(Build.ArtifactStagingDirectory)\Artifacts
    verbosityPack: Minimal
  displayName: Pack

- task: PowerShell@2
  displayName: Authenticode Sign artifacts
  inputs:
    filePath: Scripts/Sign-Package.ps1
  env:
    SignClientUser: $(SignClientUser)
    SignClientSecret: $(SignClientSecret)
    ArtifactDirectory: $(Build.ArtifactStagingDirectory)\Artifacts
  condition: and(succeeded(), not(eq(variables['build.reason'], 'PullRequest')), not(eq(variables['SignClientSecret'], '')), not(eq(variables['SignClientUser'], '')))

- task: PublishBuildArtifacts@1
  displayName: Publish Build Artifacts
  inputs:
    pathToPublish: $(Build.ArtifactStagingDirectory)\Artifacts
    artifactType: container
    artifactName: Artifacts
